version: "2"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    volumes: 
      - ./DataForDB:/data-for-db
      - ./sql:/docker-entrypoint-initdb.d
    restart: always


#  adminer:
#    image: clue/adminer
#    ports:
#      - 8081:80

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      DB_CONNSTRING: postgresql://root:root@db:5432/root
