version: "3"
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    volumes: 
      - ./DataForDB:/data-for-db
    restart: always

  prisma:
    image: prismagraphql/prisma:1.17
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            database: root
            schema: public
            user: root
            password: root
            migrations: false
            ssl: false

  adminer:
    image: clue/adminer
    ports:
      - 8081:80

  app:
    build: .
    ports:
      - 8080:8080
    environment:
      # PRISMA_URL: http://ec2-18-188-88-0.us-east-2.compute.amazonaws.com:4466
      PRISMA_URL: http://prisma:4466
